name: Build & Deploy Quarkdown

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Quarkdown
        uses: quarkdown-labs/setup-quarkdown@v1

      - name: Compile Quarkdown (FULL SITE)
        run: |
          rm -rf output
          mkdir -p output
          quarkdown c Informe_Final_Control.qd -o output/

      - name: Debug output (opcional)
        run: |
          echo "Contenido generado:"
          ls -R output

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
